"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export default function Page() {
  const [form, setForm] = useState({
    title: "",
    department: "",
    level: "",
    duration: "",
    credits: "",
    description: "",
    objectives: "",
    audience: "",
    method: "",
    assessment: "",
    style: "",
  });

  const [output, setOutput] = useState("");

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const generateCurriculum = async () => {
    // Gemini AI API-ready prompt (mocked response for production demo)
    const curriculum = `COURSE TITLE: ${form.title}\n\nDEPARTMENT: ${form.department}\nLEVEL: ${form.level}\nDURATION: ${form.duration}\nCREDIT LOAD: ${form.credits}\n\nCOURSE DESCRIPTION:\n${form.description}\n\nLEARNING OBJECTIVES:\n${form.objectives}\n\nTARGET AUDIENCE:\n${form.audience}\n\nTEACHING METHOD:\n${form.method}\n\nASSESSMENT METHODS:\n${form.assessment}\n\n--- AI-GENERATED CURRICULUM OUTLINE ---\n\nWeek 1: Course Introduction & Foundations\n- Course scope and expectations\n- Overview of assessments\n\nWeek 2: Core Concepts\n- Key theories and frameworks\n- Examples and discussion\n\nWeek 3: Applied Learning\n- Case studies\n- Practical activities\n\nWeek 4: Evaluation & Review\n- Project presentations\n- Course wrap-up\n\nCurriculum Style: ${form.style}\n\nGenerated by Gemini AI • Personal Portfolio Product`;

    setOutput(curriculum);
  };

  return (
    <main className="min-h-screen bg-gray-50 p-8">
      <header className="mb-8">
        <h1 className="text-4xl font-bold">AI Lecturer Curriculum Generator</h1>
        <p className="text-gray-600 mt-2">
          A personal AI product by Esther Alo • Powered by Gemini AI
        </p>
      </header>

      <section className="grid gap-8 md:grid-cols-2">
        <Card>
          <CardContent className="space-y-4 pt-6">
            <Input name="title" placeholder="Course Title" onChange={handleChange} />
            <Input name="department" placeholder="Department / Faculty" onChange={handleChange} />
            <Input name="level" placeholder="Course Level" onChange={handleChange} />
            <Input name="duration" placeholder="Course Duration" onChange={handleChange} />
            <Input name="credits" placeholder="Credit Load" onChange={handleChange} />
            <Textarea name="description" placeholder="Course Description" onChange={handleChange} />
            <Textarea name="objectives" placeholder="Learning Objectives" onChange={handleChange} />
            <Input name="audience" placeholder="Target Audience" onChange={handleChange} />
            <Input name="method" placeholder="Teaching Method" onChange={handleChange} />
            <Input name="assessment" placeholder="Assessment Methods" onChange={handleChange} />
            <Input name="style" placeholder="Preferred Curriculum Style" onChange={handleChange} />

            <Button className="w-full" onClick={generateCurriculum}>
              Generate Curriculum
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <h2 className="text-xl font-semibold mb-2">Generated Curriculum</h2>
            <pre className="whitespace-pre-wrap text-sm bg-white p-4 rounded-lg shadow-inner min-h-[420px]">
              {output || "Your AI-generated curriculum will appear here."}
            </pre>
          </CardContent>
        </Card>
      </section>

      <footer className="mt-12 text-center text-sm text-gray-500">
        © {new Date().getFullYear()} Esther Alo • AI Product Portfolio
      </footer>
    </main>
  );
}
